### ISSUE TITLE
Should `mir init` create labels.csv?

### ISSUE THREAD

**Issue by liyi93319** [IndustryEssentials/ymir#1335]
**Describe the issue**
per doc https://github.com/IndustryEssentials/ymir#422-create-local-repo-and-import-data

`mir init` creates "labels.csv" though, it actually doesn't.

**To Reproduce**
1. `mkdir ~/mir-demo-repo && cd ~/mir-demo-repo`
2. `mir init`

**Expected behavior**
the file ~/mir-demo-repo/labels.csv exists

**Additional context**

```
$ ls -a
.  ..  .git  .gitattributes  .gitignore  .mir
```

**Comment by fenrir-z** [comment]
it creates labels.yaml in .mir directory.

can you see that file?

**Comment by liyi93319** [comment]
yes, I see the file, here is the contents

```
labels: []
ymir_version: 2.0.0
```

**Comment by fenrir-z** [comment]
ok, that's what your need.

if you want to add your own labels, you can edit this file, just like:

``` yaml
labels:
- id: 0
  name: cat
  aliases: []
- id: 1
  name: tv
  aliases:
  - tvmonitor
  - television
ymir_version: 2.0.0
```
